"""empty message

Revision ID: 141f9ca1be81
Revises: 7d99545fc38d
Create Date: 2026-01-16 10:38:57.299935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141f9ca1be81'
down_revision = '7d99545fc38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorites_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorites_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_starship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('favorites_id', sa.Integer(), nullable=False),
    sa.Column('starship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites_character')
    op.drop_table('favorites_starship')
    op.drop_table('favorites_planet')
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diameter', sa.Integer(), nullable=False))
        batch_op.drop_constraint('planet_diametre_key', type_='unique')
        batch_op.create_unique_constraint(None, ['diameter'])
        batch_op.drop_column('diametre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diametre', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('planet_diametre_key', ['diametre'])
        batch_op.drop_column('diameter')

    op.create_table('favorites_planet',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('favorites_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], name='favorites_planet_favorites_id_fkey'),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='favorites_planet_planet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_planet_pkey')
    )
    op.create_table('favorites_starship',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('favorites_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('starship_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], name='favorites_starship_favorites_id_fkey'),
    sa.ForeignKeyConstraint(['starship_id'], ['starship.id'], name='favorites_starship_starship_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_starship_pkey')
    )
    op.create_table('favorites_character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('favorites_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='favorites_character_character_id_fkey'),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], name='favorites_character_favorites_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorites_character_pkey')
    )
    op.drop_table('favorite_starship')
    op.drop_table('favorite_planet')
    op.drop_table('favorite_character')
    # ### end Alembic commands ###
