"""empty message

Revision ID: 393ffe846fc8
Revises: dca3804a6a64
Create Date: 2026-01-13 13:22:15.939844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393ffe846fc8'
down_revision = 'dca3804a6a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
