"""empty message

Revision ID: dca3804a6a64
Revises: 0c61f62814b2
Create Date: 2026-01-13 12:54:01.164153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca3804a6a64'
down_revision = '0c61f62814b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=90), nullable=False))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['lastname'])
        batch_op.create_unique_constraint(None, ['height'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('diametre', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['climate'])
        batch_op.create_unique_constraint(None, ['diametre'])

    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crew', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('manufacturer', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['crew'])
        batch_op.create_unique_constraint(None, ['manufacturer'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('starship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('crew')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('diametre')
        batch_op.drop_column('climate')

    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('height')
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
